-- 1
SELECT ID, NAME FROM CUSTOMER;

-- 2
SELECT DISTINCT GRADE FROM CUSTOMER;

-- 3
SELECT * FROM CUSTOMER ORDER BY ID DESC;

-- 4
SELECT NAME FROM CUSTOMER WHERE AGE IS NULL;

-- 5
SELECT NAME FROM CUSTOMER WHERE AGE IS NOT NULL;